[package]
name = "agner-actor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1"
thiserror = "^1"
pin-project = "^1"
tokio = {version = "^1", features = ["sync"]}